# Generated by Django 4.1.1 on 2022-10-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('classe', models.CharField(max_length=100, null=True)),
                ('proficiencies', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
