# Generated by Django 4.1.1 on 2022-10-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character',
            new_name='PJ',
        ),
    ]
