# Generated by Django 4.1.1 on 2022-10-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
