# Generated by Django 4.1.1 on 2022-10-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0002_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='classe',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
