# Generated by Django 4.1.1 on 2022-10-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0003_rename_name_pj_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pj',
            name='proficiencies',
        ),
    ]
