# Generated by Django 4.1.1 on 2022-10-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0006_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
