# Generated by Django 4.1.1 on 2022-10-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0008_caracteristique'),
    ]

    operations = [
        migrations.AddField(
            model_name='pj',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PJ', to='charSheet.classe'),
        ),
    ]
