# Generated by Django 4.1.1 on 2022-10-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0011_caracteristique_desc_classe_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='competences_choices',
            field=models.ManyToManyField(to='charSheet.competence'),
        ),
        migrations.AddField(
            model_name='classe',
            name='dv',
            field=models.IntegerField(null=True),
        ),
    ]
