# Generated by Django 4.1.1 on 2022-10-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0012_classe_competences_choices_classe_dv'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='jets_sauvegarde',
            field=models.ManyToManyField(to='charSheet.caracteristique'),
        ),
    ]
