# Generated by Django 4.1.1 on 2022-10-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0013_classe_jets_sauvegarde'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristique',
            name='nom',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
