# Generated by Django 4.1.1 on 2022-10-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0015_alter_caracteristique_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='competences_choices',
            new_name='choix_competences',
        ),
    ]
