# Generated by Django 4.1.1 on 2022-10-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0016_rename_competences_choices_classe_choix_competences'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='nb_competences',
            field=models.IntegerField(null=True),
        ),
    ]
