# Generated by Django 4.1.1 on 2022-10-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0017_classe_nb_competences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='nb_competences',
            field=models.IntegerField(default=2),
        ),
    ]
