# Generated by Django 4.1.1 on 2022-10-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0020_alter_race_bonus_caracteristique'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='SousRace',
            fields=[
                ('race_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charSheet.race')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_race', to='charSheet.race')),
            ],
            bases=('charSheet.race',),
        ),
    ]
