# Generated by Django 4.1.1 on 2022-10-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0021_race_desc_sousrace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='taille_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='taille_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='vitesse',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
