# Generated by Django 4.1.1 on 2022-10-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0022_alter_race_desc_alter_race_taille_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='vitesse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
