# Generated by Django 4.1.1 on 2022-10-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0023_alter_race_vitesse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SousRace',
        ),
    ]
