# Generated by Django 4.1.1 on 2022-10-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0024_delete_sousrace'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='capacite',
            field=models.ManyToManyField(to='charSheet.racecapacite'),
        ),
    ]
