# Generated by Django 4.1.1 on 2022-10-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0025_race_capacite'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='famille',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
