# Generated by Django 4.1.1 on 2022-10-26 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0026_race_famille'),
    ]

    operations = [
        migrations.AddField(
            model_name='pj',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PJs', to='charSheet.race'),
        ),
    ]
