# Generated by Django 4.1.1 on 2022-10-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0027_pj_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='pj',
            name='caracteristique',
            field=models.ManyToManyField(through='charSheet.ValeurCaracteristique', to='charSheet.caracteristique'),
        ),
    ]
