# Generated by Django 4.1.1 on 2022-10-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0028_pj_caracteristique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pj',
            name='caracteristique',
        ),
        migrations.AddField(
            model_name='pj',
            name='force',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
