# Generated by Django 4.1.1 on 2022-10-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0029_remove_pj_caracteristique_pj_force'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pj',
            name='force',
        ),
    ]
