# Generated by Django 4.1.1 on 2022-10-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0030_remove_pj_force'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaractForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='competence',
            name='charisme',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competence',
            name='constitution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competence',
            name='dexterite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competence',
            name='force',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competence',
            name='intelligence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competence',
            name='sagesse',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
