# Generated by Django 4.1.1 on 2022-10-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0032_remove_competence_charisme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(null=True)),
                ('competences', models.ManyToManyField(to='charSheet.competence')),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outil',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CaractForm',
        ),
        migrations.AddField(
            model_name='historique',
            name='langue',
            field=models.ManyToManyField(to='charSheet.langue'),
        ),
        migrations.AddField(
            model_name='historique',
            name='outils',
            field=models.ManyToManyField(to='charSheet.outil'),
        ),
    ]
