# Generated by Django 4.1.1 on 2022-10-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0034_equipement_quantiteequipement'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='po',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
