# Generated by Django 4.1.1 on 2022-10-26 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0035_historique_po_alter_equipement_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pj',
            name='historique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PJs', to='charSheet.historique'),
        ),
    ]
