# Generated by Django 4.1.1 on 2022-10-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0036_pj_historique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='choix_competences',
            field=models.ManyToManyField(related_name='classes', to='charSheet.competence'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='competences',
            field=models.ManyToManyField(related_name='historiques', to='charSheet.competence'),
        ),
    ]
