# Generated by Django 4.1.1 on 2022-11-02 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0037_alter_classe_choix_competences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Des',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProprieteArme',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_degat',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='poids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Arme',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charSheet.equipement')),
                ('nb_des', models.IntegerField(default=1)),
                ('degat', models.CharField(blank=True, max_length=5, null=True)),
                ('des_degat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charSheet.des')),
                ('propriete', models.ManyToManyField(to='charSheet.proprietearme')),
                ('type_degat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charSheet.type_degat')),
            ],
            bases=('charSheet.equipement',),
        ),
    ]
