# Generated by Django 4.1.1 on 2022-11-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0039_rename_id_des_valeur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Des',
            new_name='De',
        ),
    ]
