# Generated by Django 4.1.1 on 2022-11-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0040_rename_des_de'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipement',
            old_name='price',
            new_name='prix',
        ),
    ]
