# Generated by Django 4.1.1 on 2022-11-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0041_rename_price_equipement_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='prix',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
