# Generated by Django 4.1.1 on 2022-11-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0042_alter_equipement_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='arme',
            name='portee_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arme',
            name='portee_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
