# Generated by Django 4.1.1 on 2022-11-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0043_arme_portee_max_arme_portee_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieArme',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
