# Generated by Django 4.1.1 on 2022-11-02 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0044_categoriearme'),
    ]

    operations = [
        migrations.AddField(
            model_name='arme',
            name='categorie',
            field=models.ForeignKey(default='Armes de guerre à distance', on_delete=django.db.models.deletion.PROTECT, to='charSheet.categoriearme'),
        ),
    ]
