# Generated by Django 4.1.1 on 2022-11-02 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0045_arme_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arme',
            name='categorie',
            field=models.ForeignKey(default='Armes courantes de corps à corps', on_delete=django.db.models.deletion.PROTECT, to='charSheet.categoriearme'),
        ),
    ]
