# Generated by Django 4.1.1 on 2022-11-02 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0046_alter_arme_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arme',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charSheet.categoriearme'),
        ),
        migrations.AlterField(
            model_name='arme',
            name='des_degat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charSheet.de'),
        ),
        migrations.AlterField(
            model_name='arme',
            name='type_degat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charSheet.type_degat'),
        ),
    ]
