# Generated by Django 4.1.1 on 2022-11-02 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0047_alter_arme_categorie_alter_arme_des_degat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arme',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='arme',
            name='des_degat',
        ),
        migrations.RemoveField(
            model_name='arme',
            name='nb_des',
        ),
        migrations.RemoveField(
            model_name='arme',
            name='type_degat',
        ),
        migrations.DeleteModel(
            name='CategorieArme',
        ),
        migrations.DeleteModel(
            name='De',
        ),
        migrations.DeleteModel(
            name='Type_degat',
        ),
    ]
