# Generated by Django 4.1.1 on 2022-11-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0048_remove_arme_categorie_remove_arme_des_degat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arme',
            name='type_degat',
            field=models.CharField(choices=[(None, '(Aucun)'), ('CTD', 'contondant'), ('PRF', 'perforant'), ('TRC', 'tranchant')], max_length=3, null=True),
        ),
    ]
