# Generated by Django 4.1.1 on 2022-11-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0049_arme_type_degat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arme',
            name='degat',
            field=models.CharField(blank=True, default='PRF', max_length=5, null=True),
        ),
    ]
