# Generated by Django 4.1.1 on 2022-11-03 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0052_delete_outil_alter_arme_type_degat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outil',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charSheet.equipement')),
                ('type', models.CharField(choices=[('INS', 'Instrument de musique'), ('JEU', 'jeux'), ('KIT', 'kit'), ('OUT', "outils d'artisan"), ('VEH', 'vehicule')], default='OUT', max_length=3)),
            ],
            bases=('charSheet.equipement',),
        ),
    ]
