# Generated by Django 4.1.1 on 2022-11-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0053_outil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='type',
            field=models.CharField(choices=[('INS', 'Instrument de musique'), ('JEU', 'jeu'), ('KIT', 'kit'), ('OUT', "outils d'artisan"), ('VEH', 'vehicule')], default='OUT', max_length=3),
        ),
    ]
