# Generated by Django 4.1.1 on 2022-11-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0054_alter_outil_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armure',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charSheet.equipement')),
                ('CA', models.IntegerField(blank=True, null=True)),
                ('mod_dext', models.IntegerField(blank=True, choices=[(1, 'mod.dex'), (2, 'mod.dex(+2max)'), (None, 'aucun')], null=True)),
                ('discretion_desavantage', models.BooleanField(default=False)),
                ('force_min', models.IntegerField(blank=True, null=True)),
                ('categorie', models.CharField(choices=[('LGR', 'Légère'), ('INT', 'Intermédiaire'), ('LRD', 'Lourde'), ('BCL', 'Bouclier')], max_length=3)),
            ],
            bases=('charSheet.equipement',),
        ),
    ]
